# Problem 2 
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
def fibonacci(num)
    x = 1
    y = 2
    @fib = [1,2]
    while x&&y<num
        if x+y<num
            @fib<<x+=y
        else
            break
        end
        if y+x<num       
            @fib<<y+=x
        else
            break
        end        
    end
    evens
end

def evens
    @even = Array.new
    @fib.each do |x|
        if x %2 == 0
            @even<<x
        else
        end
    end
    puts @even
    add_array
end

def add_array
    @even = @even.inject(0){|sum,x| sum + x }
    puts @even
end  

fibonacci(4000000)



